"""Protocol interfaces shared by real modules and fakes."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from swarm.contracts.mission import GraphProposal, Mission, TaskAttempt, TaskSpec
from swarm.contracts.provider import AttemptReceipt, InferenceRequest, Reservation, RouteSnapshot
from swarm.contracts.workspace import (
    ActionReceipt,
    ArtifactRef,
    ContextBundle,
    EvalResult,
    Finding,
    ToolCall,
    WorkerLease,
)


@runtime_checkable
class ProviderAdapter(Protocol):
    async def discover(self) -> list[RouteSnapshot]: ...
    async def inspect_account(self, account_id: str) -> dict[str, Any]: ...
    async def describe_route(self, route_id: str) -> RouteSnapshot: ...
    async def execute_one(
        self, request: InferenceRequest, admitted_ticket: Reservation
    ) -> AttemptReceipt: ...
    async def normalize_usage(self, raw: dict[str, Any]) -> dict[str, Any]: ...
    async def classify_error(self, exc: Exception) -> str: ...


@runtime_checkable
class InferenceBroker(Protocol):
    async def assess(self, request: InferenceRequest) -> list[RouteSnapshot]: ...
    async def reserve(self, request: InferenceRequest, route: RouteSnapshot) -> Reservation: ...
    async def invoke(self, ticket: Reservation) -> AttemptReceipt: ...
    async def reconcile(self, receipt: AttemptReceipt) -> AttemptReceipt: ...
    async def explain(self, decision_id: str) -> dict[str, Any]: ...


@runtime_checkable
class CapabilityEvaluator(Protocol):
    async def build_model_input(self, case: dict[str, Any]) -> dict[str, Any]: ...
    async def evaluate_output(self, case_private: dict[str, Any], response: Any) -> EvalResult: ...
    async def record_result(self, result: EvalResult) -> None: ...
    async def qualification_for(self, task: TaskSpec, route: RouteSnapshot) -> dict[str, Any]: ...


@runtime_checkable
class Runtime(Protocol):
    async def run_task(
        self, task: TaskSpec, context: ContextBundle, lease: WorkerLease
    ) -> TaskAttempt: ...
    async def resume(self, checkpoint: str) -> TaskAttempt: ...
    async def request_cancel(self, attempt_id: str) -> None: ...


@runtime_checkable
class Controller(Protocol):
    async def submit_mission(self, mission: Mission) -> Mission: ...
    async def propose_graph_change(self, proposal: GraphProposal) -> GraphProposal: ...
    async def commit_validated_revision(self, proposal_id: str) -> int: ...
    async def choose_ready_work(self, mission_id: str) -> list[TaskSpec]: ...
    async def record_verification(self, attempt_id: str, receipt_id: str) -> None: ...
    async def reconcile_leases(self, mission_id: str) -> None: ...


@runtime_checkable
class Workspace(Protocol):
    async def append_finding(self, finding: Finding) -> Finding: ...
    async def query_scoped(self, scopes: list[str], query: str) -> list[Finding]: ...
    async def build_context(self, task: TaskSpec) -> ContextBundle: ...
    async def put_artifact(self, artifact: ArtifactRef, content: bytes) -> ArtifactRef: ...
    async def resolve_artifact(self, artifact_id: str) -> ArtifactRef: ...


@runtime_checkable
class WorkerRegistry(Protocol):
    async def register(self, lease: WorkerLease) -> WorkerLease: ...
    async def heartbeat(self, worker_id: str, generation: int) -> WorkerLease: ...
    async def claim_dispatch(self, worker_id: str) -> TaskSpec | None: ...
    async def drain(self, worker_id: str) -> WorkerLease: ...
    async def revoke_generation(self, worker_id: str) -> int: ...


@runtime_checkable
class ToolGateway(Protocol):
    async def validate(self, call: ToolCall) -> ToolCall: ...
    async def authorize(self, call: ToolCall) -> ToolCall: ...
    async def execute_or_reconcile(self, call: ToolCall) -> ActionReceipt: ...
    async def receipt(self, operation_id: str) -> ActionReceipt: ...
