"""p02_initial_domain_schema

Revision ID: 9eb193b10f4e
Revises: 
Create Date: 2026-09-19 20:35:52.361567

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eb193b10f4e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('permitted_operation', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=256), nullable=False),
    sa.Column('grantor', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_payload_hash'), 'approvals', ['payload_hash'], unique=False)
    op.create_table('artifact_metadata',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('byte_length', sa.BigInteger(), nullable=False),
    sa.Column('owner_scope', sa.String(length=64), nullable=False),
    sa.Column('retention_class', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', 'owner_scope', name='uq_artifact_hash_scope')
    )
    op.create_index(op.f('ix_artifact_metadata_content_hash'), 'artifact_metadata', ['content_hash'], unique=False)
    op.create_index(op.f('ix_artifact_metadata_owner_scope'), 'artifact_metadata', ['owner_scope'], unique=False)
    op.create_index(op.f('ix_artifact_metadata_retention_class'), 'artifact_metadata', ['retention_class'], unique=False)
    op.create_table('attempt_receipts',
    sa.Column('network_attempt_id', sa.String(length=64), nullable=False),
    sa.Column('logical_call_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('actual_route', sa.String(length=64), nullable=False),
    sa.Column('send_phase', sa.String(length=32), nullable=False),
    sa.Column('settlement_state', sa.String(length=32), nullable=False),
    sa.Column('error_class', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('network_attempt_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_receipt_idempotency'),
    sa.UniqueConstraint('logical_call_id', 'network_attempt_id', name='uq_receipt_call_attempt')
    )
    op.create_index(op.f('ix_attempt_receipts_logical_call_id'), 'attempt_receipts', ['logical_call_id'], unique=False)
    op.create_index(op.f('ix_attempt_receipts_settlement_state'), 'attempt_receipts', ['settlement_state'], unique=False)
    op.create_table('capability_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('profile_key', sa.String(length=512), nullable=False),
    sa.Column('route_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('task_family', sa.String(length=64), nullable=False),
    sa.Column('routing_state', sa.String(length=32), nullable=False),
    sa.Column('distinct_case_count', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_key', name='uq_capability_profile_key')
    )
    op.create_index(op.f('ix_capability_profiles_route_fingerprint'), 'capability_profiles', ['route_fingerprint'], unique=False)
    op.create_index(op.f('ix_capability_profiles_task_family'), 'capability_profiles', ['task_family'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('attempt_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_event_dedupe')
    )
    op.create_index(op.f('ix_events_mission_id'), 'events', ['mission_id'], unique=False)
    op.create_index('ix_events_project_occurred', 'events', ['project_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('artifact_ref', sa.String(length=64), nullable=True),
    sa.Column('acl', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_mission_id'), 'findings', ['mission_id'], unique=False)
    op.create_index(op.f('ix_findings_project_id'), 'findings', ['project_id'], unique=False)
    op.create_index('ix_findings_project_task', 'findings', ['project_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_task_id'), 'findings', ['task_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('cancellation_generation', sa.Integer(), nullable=False),
    sa.Column('resource_policy_id', sa.String(length=64), nullable=False),
    sa.Column('max_wall_time_seconds', sa.Integer(), nullable=False),
    sa.Column('max_graph_nodes', sa.Integer(), nullable=False),
    sa.Column('max_active_sessions', sa.Integer(), nullable=False),
    sa.Column('max_model_calls', sa.Integer(), nullable=False),
    sa.Column('total_token_envelope', sa.Integer(), nullable=True),
    sa.Column('acceptance_receipt_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_project_id'), 'missions', ['project_id'], unique=False)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('stable_workflow_id', sa.String(length=128), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stable_workflow_id', name='uq_outbox_workflow_id')
    )
    op.create_index(op.f('ix_outbox_aggregate_id'), 'outbox', ['aggregate_id'], unique=False)
    op.create_index('ix_outbox_status_created', 'outbox', ['status', 'created_at'], unique=False)
    op.create_table('provider_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('account_alias', sa.String(length=128), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('account_status', sa.String(length=32), nullable=False),
    sa.Column('purpose_eligibility', sa.String(length=32), nullable=False),
    sa.Column('billing_mode', sa.String(length=32), nullable=False),
    sa.Column('secret_ref_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_accounts_service_id'), 'provider_accounts', ['service_id'], unique=False)
    op.create_table('quota_buckets',
    sa.Column('bucket_id', sa.String(length=64), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.Column('window_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bucket_id')
    )
    op.create_index(op.f('ix_quota_buckets_scope_id'), 'quota_buckets', ['scope_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.String(length=64), nullable=False),
    sa.Column('logical_call_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('fence_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('logical_call_id', name='uq_reservation_logical_call')
    )
    op.create_index(op.f('ix_reservations_attempt_id'), 'reservations', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_reservations_route_id'), 'reservations', ['route_id'], unique=False)
    op.create_table('route_snapshots',
    sa.Column('route_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('billing_origin', sa.String(length=64), nullable=False),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_route_snapshots_account_id'), 'route_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_route_snapshots_provider'), 'route_snapshots', ['provider'], unique=False)
    op.create_table('worker_leases',
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('node_identity', sa.String(length=128), nullable=False),
    sa.Column('architecture', sa.String(length=32), nullable=False),
    sa.Column('runtime_version', sa.String(length=32), nullable=False),
    sa.Column('capacity_units', sa.Float(), nullable=False),
    sa.Column('lease_generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index(op.f('ix_worker_leases_node_identity'), 'worker_leases', ['node_identity'], unique=False)
    op.create_index(op.f('ix_worker_leases_status'), 'worker_leases', ['status'], unique=False)
    op.create_table('graph_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('based_on_revision', sa.Integer(), nullable=False),
    sa.Column('author_session_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('rationale_summary', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'revision', name='uq_graph_mission_revision')
    )
    op.create_index(op.f('ix_graph_revisions_mission_id'), 'graph_revisions', ['mission_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('parent_task_id', sa.String(length=64), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('task_family', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('graph_revision', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependency_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_mission_id'), 'tasks', ['mission_id'], unique=False)
    op.create_index('ix_tasks_mission_status', 'tasks', ['mission_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_family'), 'tasks', ['task_family'], unique=False)
    op.create_table('task_attempts',
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('agent_profile_id', sa.String(length=64), nullable=False),
    sa.Column('selected_route_id', sa.String(length=64), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('lease_generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('verification_receipt_id', sa.String(length=64), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_task_attempts_status'), 'task_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_task_attempts_task_id'), 'task_attempts', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_attempts_task_id'), table_name='task_attempts')
    op.drop_index(op.f('ix_task_attempts_status'), table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_index(op.f('ix_tasks_task_family'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index('ix_tasks_mission_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_mission_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_graph_revisions_mission_id'), table_name='graph_revisions')
    op.drop_table('graph_revisions')
    op.drop_index(op.f('ix_worker_leases_status'), table_name='worker_leases')
    op.drop_index(op.f('ix_worker_leases_node_identity'), table_name='worker_leases')
    op.drop_table('worker_leases')
    op.drop_index(op.f('ix_route_snapshots_provider'), table_name='route_snapshots')
    op.drop_index(op.f('ix_route_snapshots_account_id'), table_name='route_snapshots')
    op.drop_table('route_snapshots')
    op.drop_index(op.f('ix_reservations_route_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_attempt_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_quota_buckets_scope_id'), table_name='quota_buckets')
    op.drop_table('quota_buckets')
    op.drop_index(op.f('ix_provider_accounts_service_id'), table_name='provider_accounts')
    op.drop_table('provider_accounts')
    op.drop_index('ix_outbox_status_created', table_name='outbox')
    op.drop_index(op.f('ix_outbox_aggregate_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_project_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_findings_task_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index('ix_findings_project_task', table_name='findings')
    op.drop_index(op.f('ix_findings_project_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_mission_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index('ix_events_project_occurred', table_name='events')
    op.drop_index(op.f('ix_events_mission_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_capability_profiles_task_family'), table_name='capability_profiles')
    op.drop_index(op.f('ix_capability_profiles_route_fingerprint'), table_name='capability_profiles')
    op.drop_table('capability_profiles')
    op.drop_index(op.f('ix_attempt_receipts_settlement_state'), table_name='attempt_receipts')
    op.drop_index(op.f('ix_attempt_receipts_logical_call_id'), table_name='attempt_receipts')
    op.drop_table('attempt_receipts')
    op.drop_index(op.f('ix_artifact_metadata_retention_class'), table_name='artifact_metadata')
    op.drop_index(op.f('ix_artifact_metadata_owner_scope'), table_name='artifact_metadata')
    op.drop_index(op.f('ix_artifact_metadata_content_hash'), table_name='artifact_metadata')
    op.drop_table('artifact_metadata')
    op.drop_index(op.f('ix_approvals_payload_hash'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
