#!/usr/bin/env python3
"""Generate a local compose .env with a random Postgres password (V2A-H6A / H6A-R).

Writes ``deploy/compose/.env`` (gitignored) owner-only (``0600`` on POSIX).
Does not print the secret. Does not start containers or claim public deployment.

``--force`` regenerates a *fresh local config only*. It is **not** safe credential
rotation for an already-initialized Postgres volume — a new password will
desynchronize from an existing DB role unless the volume is wiped/recreated.
"""

from __future__ import annotations

import argparse
import os
import secrets
import stat
import sys
from datetime import UTC, datetime
from pathlib import Path
from urllib.parse import quote_plus

REPO = Path(__file__).resolve().parents[1]
COMPOSE_DIR = REPO / "deploy" / "compose"
ENV_PATH = COMPOSE_DIR / ".env"
_OWNER_ONLY = 0o600


def _chmod_owner_only(path: Path) -> None:
    """Best-effort owner-only mode; no-op on platforms without chmod semantics."""
    try:
        os.chmod(path, _OWNER_ONLY)
    except OSError:
        # Non-POSIX / unsupported — still wrote the file; tests skip when inapplicable.
        pass


def _mode(path: Path) -> int | None:
    try:
        return stat.S_IMODE(path.stat().st_mode)
    except OSError:
        return None


def generate(
    *,
    force: bool = False,
    acknowledge_fresh_config: bool = False,
) -> Path:
    if ENV_PATH.exists() and not force:
        raise SystemExit(
            f"{ENV_PATH} already exists; pass --force --acknowledge-fresh-config "
            "to regenerate a fresh local compose config (NOT safe DB credential rotation)"
        )
    if force and ENV_PATH.exists() and not acknowledge_fresh_config:
        raise SystemExit(
            "--force requires --acknowledge-fresh-config: regenerating deploy/compose/.env "
            "creates a new password/DSN and is NOT safe rotation of an already-initialized "
            "Postgres volume (role password would desynchronize). Wipe/recreate the volume "
            "separately if you intend a fresh database, or edit credentials manually."
        )
    if force and ENV_PATH.exists():
        stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
        backup = ENV_PATH.with_name(f".env.pre-force-{stamp}")
        ENV_PATH.replace(backup)
        _chmod_owner_only(backup)

    password = secrets.token_urlsafe(24)
    user = "swarm"
    db = "swarm"
    # In-compose DSN uses service hostname `db`.
    dsn = f"postgresql+psycopg://{user}:{quote_plus(password)}@db:5432/{db}"
    content = (
        "# Generated by scripts/generate_compose_env.py — do not commit\n"
        "# Fresh local compose config only — not proof of DB credential rotation.\n"
        f"SWARM_POSTGRES_USER={user}\n"
        f"SWARM_POSTGRES_PASSWORD={password}\n"
        f"SWARM_POSTGRES_DB={db}\n"
        f"SWARM_DATABASE_URL={dsn}\n"
        "SWARM_BIND_HOST=127.0.0.1\n"
    )
    ENV_PATH.write_text(content)
    _chmod_owner_only(ENV_PATH)
    return ENV_PATH


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help=(
            "overwrite existing deploy/compose/.env after renaming it aside; "
            "requires --acknowledge-fresh-config (not safe initialized-DB rotation)"
        ),
    )
    parser.add_argument(
        "--acknowledge-fresh-config",
        action="store_true",
        help=(
            "required with --force; acknowledges this writes a fresh local secret/DSN "
            "and does not safely rotate credentials on an existing Postgres volume"
        ),
    )
    args = parser.parse_args(argv)
    path = generate(
        force=args.force,
        acknowledge_fresh_config=args.acknowledge_fresh_config,
    )
    # Never print the password — only the path.
    mode = _mode(path)
    mode_note = f" mode={oct(mode)}" if mode is not None else ""
    print(f"wrote {path.relative_to(REPO)} (secret not printed;{mode_note})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
