#!/usr/bin/env python3
"""Generate a local compose .env with a random Postgres password (V2A-H6A).

Writes ``deploy/compose/.env`` (gitignored). Does not print the secret.
Does not start containers or claim public deployment.
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path
from urllib.parse import quote_plus

REPO = Path(__file__).resolve().parents[1]
COMPOSE_DIR = REPO / "deploy" / "compose"
ENV_PATH = COMPOSE_DIR / ".env"


def generate(*, force: bool = False) -> Path:
    if ENV_PATH.exists() and not force:
        raise SystemExit(
            f"{ENV_PATH} already exists; pass --force to regenerate "
            "(will overwrite local secret)"
        )
    password = secrets.token_urlsafe(24)
    user = "swarm"
    db = "swarm"
    # In-compose DSN uses service hostname `db`.
    dsn = f"postgresql+psycopg://{user}:{quote_plus(password)}@db:5432/{db}"
    content = (
        "# Generated by scripts/generate_compose_env.py — do not commit\n"
        f"SWARM_POSTGRES_USER={user}\n"
        f"SWARM_POSTGRES_PASSWORD={password}\n"
        f"SWARM_POSTGRES_DB={db}\n"
        f"SWARM_DATABASE_URL={dsn}\n"
        "SWARM_BIND_HOST=127.0.0.1\n"
    )
    ENV_PATH.write_text(content)
    return ENV_PATH


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing deploy/compose/.env",
    )
    args = parser.parse_args(argv)
    path = generate(force=args.force)
    # Never print the password — only the path.
    print(f"wrote {path.relative_to(REPO)} (secret not printed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
